name: build-and-publish-workflow

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-and-push-image:
    name: Build and publish package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Set version from tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Set package version - ${{ steps.vars.outputs.tag }}
        id: write-version
        run: poetry version ${{ steps.vars.outputs.tag }}
      - name: Publish package to PyPi
        id: publish-pip
        run: |
          poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
